### ISSUE TITLE
do we have a video recording for this session?

### ISSUE THREAD

**Issue by xiaopeng163** [judy2k/refactoring-talk-pyconie2017#1]
thanks.

**Comment by judy2k** [comment]
Hi @xiaopeng163 - I only gave the talk a day after you opened this issue. The PyConIE talk is not up yet, but I gave a very similar talk at Europython this summer: https://youtu.be/4H5yNP19es8?t=2h30m16s

**Comment by xiaopeng163** [comment]
thanks, Mark, I will watch it.
